import type { Metadata } from "next";
import styles from './layout.module.css';
import '@vkontakte/vkui/dist/vkui.css';
import { getUser } from "@/utils/user";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUser();
  console.log(user);
  return (
    <html lang="en" className={styles.html}>
      <body className={styles.body}>
        {children}
      </body>
    </html>
  );
}
